apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ckubeagents.ckubeagent.io
spec:
  group: ckubeagent.io
  names:
    kind: Ckubeagent
    listKind: CkubeagentList
    plural: ckubeagents
    singular: ckubeagent
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
