kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ckubeagent-operator
subjects:
- kind: ServiceAccount
  name: ckubeagent-operator
  namespace: default
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  #  name: ckubeagent-operator
  name: cluster-admin
  apiGroup: "rbac.authorization.k8s.io"
